### ISSUE TITLE
 Not working on kibana 6.7.1 - getting $rootScope.$listen is not a function

### ISSUE THREAD

**Issue by samueltuckey** [bondib/kibana-iframe-communicator-plugin#16]
I am getting an error running the plugin on version 6.7.1

The kibana home page returns a 500 and the error is:

TypeError: $rootScope.$listen is not a function
    at new Courier (http://localhost:5601/bundles/commons.bundle.js:3:1216460)
    at new <anonymous> (http://localhost:5601/bundles/commons.bundle.js:3:1217000)
    at Object.instantiate (http://localhost:5601/built_assets/dlls/vendors.bundle.dll.js:450:53278)
    at Object.<anonymous> (http://localhost:5601/built_assets/dlls/vendors.bundle.dll.js:450:49993)
    at Object.invoke (http://localhost:5601/built_assets/dlls/vendors.bundle.dll.js:450:53093)
    at Object.enforcedReturnValue [as $get] (http://localhost:5601/built_assets/dlls/vendors.bundle.dll.js:450:49599)
    at Object.invoke (http://localhost:5601/built_assets/dlls/vendors.bundle.dll.js:450:53093)
    at http://localhost:5601/built_assets/dlls/vendors.bundle.dll.js:450:48446
    at getService (http://localhost:5601/built_assets/dlls/vendors.bundle.dll.js:450:52033)
    at injectionArgs (http://localhost:5601/built_assets/dlls/vendors.bundle.dll.js:450:52562)

Any help would be appreciated.

Regards
Sam
